service: serverless-hello-world
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs12.x

functions:
  hello:
    handler: handler.hello
    events:
      - http:
          method: get
          path: hello
